name: Print GitHub Context

on:
  issues:
    types: [opened]

jobs:
  print-context:
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub context
        run: |
          echo '${{ toJson(github) }}'
      - name: Print run URL (Enterprise safe)
        run: |
           echo "Run URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

