name: Use Multiline Env in Python

on:
  workflow_dispatch:

jobs:
  process-list:
    runs-on: ubuntu-latest

    env:
      MY_LIST: '["aaaaaaaaaaaaaaaaaaa","b"]'

    steps:
      - run: python -V
      - name: Run Python Script
        shell: python
        run: |
          import os
          import json
          import requests

          # Read and split the multiline environment variable
          items = json.loads(os.environ["MY_LIST"])

          print("List from MY_LIST env variable:")
          for i, item in enumerate(items, start=1):
              print(f"{i}. {item}")
