name: Databricks Change Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      is_even_day: ${{ steps.set-output.outputs.is_even_day }}
    steps:
      - name: "Get today's day"
        id: set-output
        run: |
          DAY=$(date +%d)
          if [ $((10#$DAY % 2)) -ne 0 ]; then
            echo "Even day: $DAY"
            echo "is_even_day=true" >> "$GITHUB_OUTPUT"
          fi
  
  path-check:
    runs-on: ubuntu-latest
    needs: check
    if: '!needs.check.outputs.is_even_day'
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes in src/
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'src/**'

  databricks-job:
    needs: [ check, path-check]
    if: '!needs.check.outputs.is_even_day'
    uses: ./.github/workflows/reusable.yml
    with:
      environment: ${{ toJSON(needs.path-check.outputs.src) }}
