name: Build and Release Workflow

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow only on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Create Output Folder and Generate a File
      - name: Create Output Folder
        run: |
          mkdir -p output
          echo "This is a sample artifact file." > output/sample.txt

      # Step 3: Upload the Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: output/

  release:
    needs: build  # Ensure this job runs after the 'build' job
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Download the Artifact
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ./release-assets

      # Step 3: Create a GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # Use the tag name to match the trigger
          release_name: Release ${{ github.ref_name }}
          body: |
            This is an automated release generated by GitHub Actions.
          draft: false
          prerelease: false

      # Step 4: Upload Release Assets
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./release-assets/sample.txt
          asset_name: sample.txt
          asset_content_type: text/plain
